/**
 * columns.ts — the CSV column list and how a reading becomes a row. One row per
 * interval per step: generator gauges and latencies on the left, the relay's
 * own `STATS` numbers on the right, so a run is one table.
 */

import { Aggregate } from './metrics.js';
import type { StatsSample } from '@crack-attack/server';

export const COLUMNS = [
  'time',
  'scenario',
  'step',
  'phase',
  'elapsedSec',
  // Populations (generator's view).
  'games',
  'playing',
  'simGames',
  'spectators',
  'idlers',
  'rooms',
  'churners',
  'abusers',
  'genSockets',
  // Latencies, ms.
  'forwardP50',
  'forwardP99',
  'forwardMax',
  'forwardMean',
  'spectatorP50',
  'spectatorP99',
  'lateJoinP99',
  'reconnectP50',
  'reconnectP99',
  'welcomeP99',
  'matchEndP99',
  'graceErrP99',
  'pushP99',
  'httpP50',
  'httpP99',
  'tickerLateP99',
  // Generator counters (per second where it reads that way).
  'msgsOutPerSec',
  'bytesOutPerSec',
  'msgsInPerSec',
  'bytesInPerSec',
  'errors',
  'fatalCloses',
  'connectFailures',
  'startFailures',
  'contiguityErrors',
  'desyncs',
  'stallTicks',
  'matchStarts',
  'matchEnds',
  'resumed',
  'forfeits',
  'lateForfeits',
  'lobbyEventsPerSec',
  'roomListsPerSec',
  'roomListBytesPerSec',
  'replaysMade',
  'runsRecorded',
  'scoreboardSkipped',
  'abuseOpened',
  'abuseClosed',
  'abuseSent',
  // Generator health (worst worker).
  'genLoopP99',
  'genLoopMax',
  'genCpuPct',
  // Relay STATS.
  'relayLoopP50',
  'relayLoopP99',
  'relayLoopMax',
  'relayCpuPct',
  'relayRssMB',
  'relayHeapMB',
  'relayFds',
  'relaySockets',
  'relayConnections',
  'relaySessions',
  'relayRooms',
  'relayPlaying',
  'relaySpectators',
  'relayDropped',
  'relayMaxLedger',
  'relayMsgsInPerSec',
  'relayMsgsOutPerSec',
  'relayBytesInPerSec',
  'relayBytesOutPerSec',
  'relayBufferedMax',
  'relayBufferedTotal',
  'sbVerifierQueued',
  'sbSubmissionsInFlight',
  'sbScoresCached',
  'sbTicketClients',
  'sbSubmitClients',
  'sbScoresClients',
  'sbReplayClients',
  'relayDbMB',
  'relayWalMB',
  // Scoreboard per-route status tally, as "route status:n …".
  'httpStatus',
] as const;

const MB = 1024 * 1024;

/** Compact the http status map for one cell. */
export function httpStatusCell(http: Readonly<Record<string, number>>): string {
  return Object.entries(http)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, n]) => `${k}:${n}`)
    .join(' ');
}

/** One CSV row from an interval's aggregate and the latest relay stats. */
export function toRow(
  scenario: string,
  step: string,
  phase: string,
  elapsedSec: number,
  agg: Aggregate,
  relay: StatsSample | null,
): Record<string, unknown> {
  const h = agg.hist;
  const g = agg.gauges;
  return {
    time: new Date().toISOString(),
    scenario,
    step,
    phase,
    elapsedSec,
    games: g.games,
    playing: g.playing,
    simGames: g.simGames,
    spectators: g.spectators,
    idlers: g.idlers,
    rooms: g.rooms,
    churners: g.churners,
    abusers: g.abusers,
    genSockets: g.sockets,
    forwardP50: h.forward.percentile(50),
    forwardP99: h.forward.percentile(99),
    forwardMax: h.forward.max,
    forwardMean: h.forward.mean,
    spectatorP50: h.spectator.percentile(50),
    spectatorP99: h.spectator.percentile(99),
    lateJoinP99: h.lateJoin.percentile(99),
    reconnectP50: h.reconnect.percentile(50),
    reconnectP99: h.reconnect.percentile(99),
    welcomeP99: h.welcome.percentile(99),
    matchEndP99: h.matchEnd.percentile(99),
    graceErrP99: h.graceError.percentile(99),
    pushP99: h.push.percentile(99),
    httpP50: h.http.percentile(50),
    httpP99: h.http.percentile(99),
    tickerLateP99: h.tickerLate.percentile(99),
    msgsOutPerSec: agg.rate('msgsOut'),
    bytesOutPerSec: agg.rate('bytesOut'),
    msgsInPerSec: agg.rate('msgsIn'),
    bytesInPerSec: agg.rate('bytesIn'),
    errors: agg.counters.errors,
    fatalCloses: agg.counters.fatalCloses,
    connectFailures: agg.counters.connectFailures,
    startFailures: agg.counters.startFailures,
    contiguityErrors: agg.counters.contiguityErrors,
    desyncs: agg.counters.desyncs,
    stallTicks: agg.counters.stallTicks,
    matchStarts: agg.counters.matchStarts,
    matchEnds: agg.counters.matchEnds,
    resumed: agg.counters.resumed,
    forfeits: agg.counters.forfeits,
    lateForfeits: agg.counters.lateForfeits,
    lobbyEventsPerSec: agg.rate('lobbyEvents'),
    roomListsPerSec: agg.rate('roomLists'),
    roomListBytesPerSec: agg.rate('roomListBytes'),
    replaysMade: agg.counters.replaysMade,
    runsRecorded: agg.counters.runsRecorded,
    scoreboardSkipped: agg.counters.scoreboardSkipped,
    abuseOpened: agg.counters.abuseOpened,
    abuseClosed: agg.counters.abuseClosed,
    abuseSent: agg.counters.abuseSent,
    genLoopP99: agg.peaks.genLoopP99,
    genLoopMax: agg.peaks.genLoopMax,
    genCpuPct: agg.peaks.genCpuPct,
    relayLoopP50: relay?.loopP50Ms,
    relayLoopP99: relay?.loopP99Ms,
    relayLoopMax: relay?.loopMaxMs,
    relayCpuPct: relay?.cpuPct,
    relayRssMB: relay ? relay.rssBytes / MB : undefined,
    relayHeapMB: relay ? relay.heapUsedBytes / MB : undefined,
    relayFds: relay?.fds ?? undefined,
    relaySockets: relay?.sockets,
    relayConnections: relay?.connections,
    relaySessions: relay?.sessions,
    relayRooms: relay?.rooms,
    relayPlaying: relay?.playing,
    relaySpectators: relay?.spectators,
    relayDropped: relay?.dropped,
    relayMaxLedger: relay?.maxLedger,
    relayMsgsInPerSec: relay?.msgsInPerSec,
    relayMsgsOutPerSec: relay?.msgsOutPerSec,
    relayBytesInPerSec: relay?.bytesInPerSec,
    relayBytesOutPerSec: relay?.bytesOutPerSec,
    relayBufferedMax: relay?.bufferedMax,
    relayBufferedTotal: relay?.bufferedTotal,
    sbVerifierQueued: relay?.scoreboard?.verifierQueued,
    sbSubmissionsInFlight: relay?.scoreboard?.submissionsInFlight,
    sbScoresCached: relay?.scoreboard?.scoresCached,
    sbTicketClients: relay?.scoreboard?.ticketClients,
    sbSubmitClients: relay?.scoreboard?.submitClients,
    sbScoresClients: relay?.scoreboard?.scoresClients,
    sbReplayClients: relay?.scoreboard?.replayClients,
    relayDbMB: relay?.dbBytes != null ? relay.dbBytes / MB : undefined,
    relayWalMB: relay?.walBytes != null ? relay.walBytes / MB : undefined,
    httpStatus: httpStatusCell(agg.http),
  };
}
